export const aiExpertiseDetails = [
  // SALES
  {
    title: "Social Media Analysis and Automated Email Generation",
    shortDescription: "Analyze social media and automate email outreach.",
    image: "/aiimage/s1.png",
    category: "sales",
    tags: ["📧", "🌐", "📊"],
    link: "/ai-expertise/social-media-analysis",
    features: ["Social media analytics", "Automated email", "Lead generation"],
  },
  {
    title: "Automate Sales Cold Calling Pipeline with Apify, GPT-4o, and WhatsApp",
    shortDescription: "Automate your sales cold calling process using AI and WhatsApp.",
    image: "/productimage/da.png",
    category: "sales",
    
    link: "/ai-expertise/sales-cold-calling",
    features: ["Cold calling automation", "WhatsApp integration", "AI-powered pipeline"],
  },
  {
    title: "Lead Generation System: Google Maps to Email Scraper with Google Sheets Export",
    shortDescription: "Scrape leads from Google Maps and export to Sheets.",
    image: "/aiimage/s2.png",
    category: "sales",
    tags: ["🗺️", "📧", "📄"],
    link: "/ai-expertise/lead-generation-google-maps",
    features: ["Google Maps scraping", "Email extraction", "Sheets export"],
  },
  // MARKETING
  {
    title: "Generate AI Viral Videos with Seedance and Upload to YouTube & Instagram",
    shortDescription: "Create and upload viral videos using AI.",
    image: "/productimage/em.png",
    category: "marketing",
    tags: ["🎥", "🤖", "📈"],
    link: "/ai-expertise/ai-viral-videos",
    features: ["Video generation", "YouTube/Instagram upload", "AI-powered"],
  },
  {
    title: "Dynamically generate a webpage from user request using OpenAI Structured Output",
    shortDescription: "Generate web pages dynamically from user input.",
    image: "/productimage/m.png",
    category: "marketing",
    tags: ["🌐", "⚡", "📝"],
    link: "/ai-expertise/dynamic-webpage-generation",
    features: ["Dynamic webpage", "OpenAI integration", "Structured output"],
  },
  {
    title: "Automated Content Marketing Intelligence with OpenAI, Ahrefs & Multi-platform Integration",
    shortDescription: "Automate content marketing intelligence across platforms.",
    image: "/productimage/sale.png",
    category: "marketing",
    tags: ["📊", "🤖", "🔗"],
    link: "/ai-expertise/content-marketing-intelligence",
    features: ["Content intelligence", "Ahrefs integration", "Multi-platform"],
  },
  {
    title: "Automate Multi-Platform Social Media Content Creation with AI",
    shortDescription: "Create and publish content across platforms with AI.",
    image: "/productimage/crm.svg",
    category: "marketing",
    tags: ["🤖", "📱", "📢"],
    link: "/ai-expertise/multi-platform-content-creation",
    features: ["Multi-platform", "AI content creation", "Scheduling"],
  },
  // SUPPORT
  {
    title: "Chat with a database using AI",
    shortDescription: "Query your database using natural language.",
    image: "/aiimage/s3.png",
    category: "support",
    tags: ["💬", "🗄️", "🤖"],
    link: "/ai-expertise/chat-with-database",
    features: ["Database chat", "Natural language queries", "AI assistant"],
  },
  {
    title: "AI-Powered WhatsApp Chatbot for Text, Voice, Images, and PDF with RAG",
    shortDescription: "Deploy a WhatsApp chatbot with advanced AI features.",
    image: "/productimage/cus.png",
    category: "support",
    tags: ["💬", "📱", "🤖"],
    link: "/ai-expertise/whatsapp-chatbot-rag",
    features: ["WhatsApp chatbot", "Text/voice/images/PDF", "RAG"],
  },
  {
    title: "Voice-Based Appointment Booking System with ElevenLabs AI and Cal.com",
    shortDescription: "Automate appointment bookings with voice AI.",
    image: "/productimage/em.png",
    category: "support",
    tags: ["📅", "🗣️", "🤖"],
    link: "/ai-expertise/voice-appointment-booking",
    features: ["Voice-based booking", "AI integration", "Cal.com"],
  },
]; 